### ISSUE TITLE
sudo setup.py install not working 

### ISSUE THREAD

**Issue by swagskillsup** [wifiphisher/roguehostapd#11]
┌─[user@parrot]─[~/Desktop/roguehostapd]
└──╼ $sudo python setup.py install
In file included from roguehostapd/hostapd-2_6/src/l2_packet/l2_packet_linux.c:15:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/filter.h:10,
                 from roguehostapd/hostapd-2_6/src/l2_packet/l2_packet_linux.c:13:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
roguehostapd/hostapd-2_6/src/ap/ieee802_11.c: In function ‘handle_assoc’:
roguehostapd/hostapd-2_6/src/ap/ieee802_11.c:2154:63: warning: ?: using integer constants in boolean context [-Wint-in-bool-context]
      sta->last_subtype == reassoc ? WLAN_FC_STYPE_REASSOC_REQ :
In file included from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211.c:26:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/sysinfo.h:5,
                 from /usr/include/linux/kernel.h:5,
                 from /usr/include/linux/netlink.h:5,
                 from /usr/include/libnl3/netlink/netlink.h:25,
                 from /usr/include/libnl3/netlink/genl/genl.h:15,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211.c:17:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
roguehostapd/hostapd-2_6/src/drivers/driver_nl80211.c: In function ‘i802_set_wds_sta’:
roguehostapd/hostapd-2_6/src/drivers/driver_nl80211.c:5946:37: warning: ‘.sta’ directive output may be truncated writing 4 bytes into a region of size between 1 and 17 [-Wformat-truncation=]
  os_snprintf(name, sizeof(name), "%s.sta%d", bss->ifname, aid);
                                     ^~~~
In file included from /usr/include/stdio.h:862,
                 from roguehostapd/hostapd-2_6/src/utils/includes.h:21,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211.c:13:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 6 and 32 bytes into a destination of size 17
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_capa.c:14:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/sysinfo.h:5,
                 from /usr/include/linux/kernel.h:5,
                 from /usr/include/linux/netlink.h:5,
                 from /usr/include/libnl3/netlink/netlink.h:25,
                 from /usr/include/libnl3/netlink/genl/genl.h:15,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_capa.c:12:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
In file included from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_event.c:14:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/sysinfo.h:5,
                 from /usr/include/linux/kernel.h:5,
                 from /usr/include/linux/netlink.h:5,
                 from /usr/include/libnl3/netlink/netlink.h:25,
                 from /usr/include/libnl3/netlink/genl/genl.h:15,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_event.c:12:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
In file included from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_monitor.c:17:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/filter.h:10,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_monitor.c:15:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_monitor.c: In function ‘nl80211_create_monitor_interface’:
roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_monitor.c:365:32: warning: ‘%s’ directive output may be truncated writing up to 16 bytes into a region of size 12 [-Wformat-truncation=]
   snprintf(buf, IFNAMSIZ, "mon.%s", drv->first_bss->ifname);
                                ^~
In file included from /usr/include/stdio.h:862,
                 from roguehostapd/hostapd-2_6/src/utils/includes.h:21,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_monitor.c:13:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 5 and 21 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_scan.c:15:
roguehostapd/hostapd-2_6/src/utils/common.h:426: warning: "__bitwise" redefined
 #define __bitwise
 
In file included from /usr/include/linux/sysinfo.h:5,
                 from /usr/include/linux/kernel.h:5,
                 from /usr/include/linux/netlink.h:5,
                 from /usr/include/libnl3/netlink/netlink.h:25,
                 from /usr/include/libnl3/netlink/genl/genl.h:15,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_nl80211_scan.c:13:
/usr/include/linux/types.h:22: note: this is the location of the previous definition
 #define __bitwise __bitwise__
 
roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c: In function ‘hostap_set_iface_flags’:
roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c:351:35: warning: ‘ap’ directive output may be truncated writing 2 bytes into a region of size between 0 and 16 [-Wformat-truncation=]
  os_snprintf(ifname, IFNAMSIZ, "%sap", drv->iface);
                                   ^~
In file included from /usr/include/stdio.h:862,
                 from roguehostapd/hostapd-2_6/src/utils/includes.h:21,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c:9:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 3 and 19 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c: In function ‘hostap_init’:
roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c:234:57: warning: ‘ap’ directive output may be truncated writing 2 bytes into a region of size between 0 and 16 [-Wformat-truncation=]
         snprintf(ifr.ifr_name, sizeof(ifr.ifr_name), "%sap", drv->iface);
                                                         ^~
In file included from /usr/include/stdio.h:862,
                 from roguehostapd/hostapd-2_6/src/utils/includes.h:21,
                 from roguehostapd/hostapd-2_6/src/drivers/driver_hostap.c:9:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 3 and 19 bytes into a destination of size 16
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
┌─[user@parrot]─[~/Desktop/roguehostapd]
└──╼ $locate rougehostapd
┌─[✗]─[user@parrot]─[~/Desktop/roguehostapd]
└──╼ $

**Comment by hash3liZer** [comment]
I'm having this very same problem.

**Comment by johhnry** [comment]
Hi all,

I am on Debian Kali linux (4.19.0-kali1-amd64) and I also have the same problem with : 
<pre><font color="#EF2929"><b>root@johk</b></font>:<font color="#729FCF"><b>~/Téléchargements/roguehostapd</b></font># python setup.py install
</pre>

<pre>In file included from <b>roguehostapd/hostapd-2_6/src/l2_packet/l2_packet_linux.c:15</b>:
<b>roguehostapd/hostapd-2_6/src/utils/common.h:426:</b> <font color="#AD7FA8"><b>warning: </b></font>&quot;__bitwise&quot; redefined
 #define __bitwise
 
In file included from <b>/usr/include/linux/filter.h:10</b>,
                 from <b>roguehostapd/hostapd-2_6/src/l2_packet/l2_packet_linux.c:13</b>:
<b>/usr/include/linux/types.h:22:</b> <font color="#34E2E2"><b>note: </b></font>this is the location of the previous definition
 #define __bitwise __bitwise__
........................................................................................
</pre>

**Comment by sophron** [comment]
These are compiler warnings. They should not affect the compilation.
