### ISSUE TITLE
no files found matching '*' under directory 'roguehostapd/'

### ISSUE THREAD

**Issue by SummerBalin** [wifiphisher/roguehostapd#13]
![_20190112165158](https://user-images.githubusercontent.com/38099628/51071448-e634dc80-168b-11e9-85fd-8648c6e0c4f3.jpg)

**Comment by Coleperler11** [comment]
Can you re open this issue? I am experiencing this exact issue right now

**Comment by Coleperler11** [comment]
I am experiencing this exact issue right now, can you re open this discussion
