### ISSUE TITLE
Please help me anyone.

### ISSUE THREAD

**Issue by muthiahraj** [wifiphisher/roguehostapd#14]
<pre>Please download it and restart the compilation.If you are on Debian-based system: &apos;apt-get install libnl-3-dev libnl-genl-3-dev&apos;.
</pre>

When I am getting this error. How to fix the issue... give me the command and download path also..

i am using kali linux 2019 version...

**Comment by username836** [comment]
apt-get install libnl-3-dev libnl-genl-3-dev

Duh!

**Comment by muthiahraj** [comment]
hi which version of kali Linux u used ....

**Comment by username836** [comment]
Help me with my issue

**Comment by sophron** [comment]
Hi. Our tools do not aim to be script-kiddie friendly.
