### ISSUE TITLE
Supporting multiple instances of roguehostapd

### ISSUE THREAD

**Issue by cyrus104** [wifiphisher/roguehostapd#2]
I would like to be able to run multiple instances of roguehostapd with different configs / SSIDs on the same channel.

**Comment by anakin1028** [comment]
Do you mean you want to use one card to support multiple SSID? Or you want to use `roguehostapd` to enable two card with different security conditions?

**Comment by cyrus104** [comment]
I'd like to use multiple SSIDs on one card. Having multiple instances would
be ideal because they could be put up and taken down as needed without
restarting the whole service.

**Comment by anakin1028** [comment]
I'm not sure if hostapd can support this kind of service. From my experience feature like multiple ssid is usually implemented in the firmware/driver and not in the user space. In other words this feature is highly dependent on the adaptor you use

**Comment by cyrus104** [comment]
Thanks for the explanation. Could an AP be implemented in something like
Python. Obviously there would be major performance limitations.
