### ISSUE TITLE
Installing wifiphisher on Macbook Air

### ISSUE THREAD

**Issue by piyusharma95** [wifiphisher/roguehostapd#3]
I am trying to install `wifiphisher' on MacOS which has the `roguehostapd' as requirement. When I try to build `roguehostapd' using the setup file it throws the error:
 `[!] libnl-genl-3-dev is not found in the system!`
The requirements for `roguehostapd`, i.e, `libnl-3-dev`, `libnl-genl-3-dev` & `libssl-dev` are not available for MacOS (refer [libnl](https://www.infradead.org/~tgr/libnl/)), then how am I supposed to install wifiphisher on MacOS?

**Comment by anakin1028** [comment]
We don't support roguehostapd in MAC OS. This module is currently supported on Kali Linux.

**Comment by L1u2c3a4s5862** [comment]
I have downloaded the wifiphisher file on my macos, but when I run python3 setup.py install, they say I need to install dnsmasq on my computer, so I install it with homebrew, but it doesn't work with it, I need to move the /usr/local/opt/dnsmasq/sbin/dnsmasq file to /usr/sbin/ file, does anyone know how to do that?

**Comment by D4vinci-007** [comment]
i try to create a **Dockerfile** after downloading  **Wifiphisher**, but also i have this error :

**" /var/folders/7_/fmh5nf_53j32wwcflbd2hks80000gn/T/tmp_netlink__b456c70/test_netlink.c:2:10: fatal error: 'netlink/netlink.h' file not found
#include <netlink/netlink.h>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev"** 


and after research the error concern the **"libnl"** 
**libnl: Linux is required for this software.**

=================
**NB:
you should be use the VM machine or the System linux 
and of cours like we know all 
the best popular system is Kali Linux**
