### ISSUE TITLE
Module error when installing

### ISSUE THREAD

**Issue by SoulTaku** [wifiphisher/roguehostapd#4]
manjaro-deepin

steps: 
 -cloned the repo
 -cd roguehostapd/
 -python setup.py install
 -got the error below:

Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    from roguehostapd.config.hostapdconfig import WHITE, RED
  File "/opt/roguehostapd/roguehostapd/config/hostapdconfig.py", line 9, in <module>
    from ConfigParser import SafeConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by anakin1028** [comment]
do you use python3 to install roguehostapd?
can you post the output of `python --version`?

**Comment by SoulTaku** [comment]
Python 3.6.4

**Comment by anakin1028** [comment]
Ok currently roguehostapd only support python2. You may install it by 
`pip2 install roguehostapd`

**Comment by SoulTaku** [comment]
thank you very much :+1:
