### ISSUE TITLE
i have problem at step python setup.py install

### ISSUE THREAD

**Issue by nadisoft** [wifiphisher/roguehostapd#5]
hey have a nice day when i write python setup.py install to finish install script hostapd i see this message
![screenshot from 2018-04-17 04-46-56](https://user-images.githubusercontent.com/11483296/38847616-202f8f62-41f2-11e8-9dec-3e47076e59a6.png)

**Comment by anakin1028** [comment]
You can follow the hint in the terminal:
`apt-get install libssl-dev`

**Comment by nadisoft** [comment]
look what i got again
![screenshot from 2018-04-17 16-33-53](https://user-images.githubusercontent.com/11483296/38883702-4109ce80-425d-11e8-9957-a442e1ea4e02.png) 
help me

**Comment by dcliss** [comment]
update your source list buddy

**Comment by dennislwy** [comment]
I am also facing same problem when trying to install. I am using Kali 2018.2, apt update and fully upgraded

![image](https://user-images.githubusercontent.com/5407099/44246333-41da6700-a1cd-11e8-81e1-d3dc06b7f449.png)

**Comment by anakin1028** [comment]
Do you install libnl-dev? Can you output the stdout: `ldconfig -p |grep libnl` ?

**Comment by dennislwy** [comment]
no source to install libnl-dev
![image](https://user-images.githubusercontent.com/5407099/44246818-c29a6280-a1cf-11e8-8ecc-f2b29dc717fd.png)

**Comment by anakin1028** [comment]
Have you tried libnl-3-dev?

**Comment by volkdeejay** [comment]
leafpad /etc/apt/sources.list 
Open 
Delete all 
Copy and past this 
deb http://http.kali.org/kali kali-rolling main contrib non-free 
Save 

apt-get update 
apt-get upgrade

**Comment by nice44** [comment]
NOTHING works !!!
