### ISSUE TITLE
Fail to install 

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/roguehostapd#7]
Tried to install `roguehostpad` from `Github` on a fresh `Kali` which prompted for additional dependencies. After installing those `python setup.py install` finally succeeds. However roguehostapd is still not installed system wide. @anakin1028 any idea why it is not working? 

[Here](https://pastebin.com/iXNMVSnM) is the output of installation in case it helps.

**Comment by anakin1028** [comment]
@blackhatmonkey can you run the `run.py` successfully? Currently `roguehostapd` is used as library for wifiphisher, so I don't copy the execution file to the /bin directory during setup.py. 

`pip install roguehostapd` should also be ok.

**Comment by blackHatMonkey** [comment]
I originally installed it using `pip` but `wifiphisher` complained about it not being installed.
```
root@kali:~/roguehostapd# pip2 install roguehostapd
Requirement already satisfied: roguehostapd in /usr/local/lib/python2.7/dist-packages
```
In which directory should I run `run.py`?

**Comment by anakin1028** [comment]
You can `cd` to the `roguehostapd` folder and run `run.py` at this folder~

If you have install roguehostapd once , looks like it will remember in the cache. You can try `pip install roguehostapd --no-cache-dir`

**Comment by blackHatMonkey** [comment]
@anakin1028 Here is the output of `run.py`:
```
root@kali:~/roguehostapd/roguehostapd# ./run.py 
Traceback (most recent call last):
  File "./run.py", line 109, in <module>
    run()
  File "./run.py", line 101, in run
    hostapd_obj.start(hostapd_dict, options)
  File "/usr/local/lib/python2.7/dist-packages/roguehostapd/apctrl.py", line 152, in start
    hostapdconfig.HOSTAPD_LIBPATH)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python2.7/dist-packages/roguehostapd/hostapd-2_6/hostapd/libhostapd.so: cannot open shared object file: No such file or directory
```

> If you have install roguehostapd once , looks like it will remember in the cache. You can try pip install roguehostapd --no-cache-dir

This is a brand new install so this should not apply.

**Comment by ISBaloch** [comment]
having OS error in 
python  setup.py install
 what is the reason?
